

##### step1 download the files 
for CHR in {1..22} X Y M
do
    FILE_URL="https://hgdownload.soe.ucsc.edu/goldenPath/hg38/phastCons470way/hg38.470way.phastCons/chr${CHR}.phastCons470way.wigFix.gz"
    FILE_NAME="chr${CHR}.phastCons470way.wigFix.gz"

    echo "Downloading: $FILE_URL"
    wget -c $FILE_URL -O $FILE_NAME
done

echo "All downloads completed!"

###### step2 Convert wig to bed

wigFix="${input_indir}/chr${CHR}.phastCons470way.wigFix.gz"
            outbed="${input_indir}/chr${CHR}.phastCons470way.hg38.bed.gz"
            zcat ${wigFix} | convert2bed --input=wig - --max-mem=20G | awk -F"\t" '{{print $1"\t"$2"\t"$3"\t"$1"_"$2"_"$3"\t"$5}}' | pigz > ${outbed}
			

###### step3 Split bed files to chunks
zcat ${input_indir}/chr${CHR}.phastCons470way.hg38.bed.gz | split -l 1000000 -d -a 3 - ${outdir}/chr${CHR}.phastCons470way.hg38.chunk_
            ls ${outdir}/chr${CHR}.phastCons470way.hg38.chunk_* | grep -v "bed" | xargs -I {} mv {} {}.bed
            ls ${outdir}/chr${CHR}.phastCons470way.hg38.chunk_* | grep "bed" | xargs -n1 -i{} pigz {}			
			

###### step4 Run liftOver every 24 files
task_idx=$1

chunks_dir="./phastCons470way_chunks/"
chain="/faststorage/project/farmgtex/pipeline/code/liftover/phastCons470way/hg38ToBosTau9.over.chain.gz"
outdir="output_liftOver_chunks"
filelist=(${chunks_dir}/*.bed.gz)
nfile=${#filelist[@]}

start_idx=$((task_idx * 24))
end_idx=$((start_idx + 23))

for (( fileidx = start_idx; fileidx <= end_idx && fileidx < nfile; fileidx++ )); do
    bedfile=${filelist[fileidx]}
    echo "Processing: ${bedfile}"

    bedprefix=$(basename "${bedfile}" .bed.gz)

    liftOver -minMatch=0.8 "${bedfile}" "${chain}" "${outdir}/${bedprefix}.hg38ToBosTau9.bed" "${outdir}/${bedprefix}.unMapped"

    pigz "${outdir}/${bedprefix}.hg38ToBosTau9.bed"
    pigz "${outdir}/${bedprefix}.unMapped"

    echo "Completed: ${bedfile}"
done

###### step5 Gene-level phastCons scores

gene_gtf="/faststorage/project/farmgtex/gtex/cattle_genome/Bos_taurus.ARS-UCD1.2.108.chr.gtf"
dir_liftOver_chunks="/faststorage/project/farmgtex/pipeline/code/liftover/phastCons470way/output_liftOver_chunks"

	## merge all bed files generated by liftOver
	mkdir /faststorage/project/farmgtex/pipeline/code/liftover/phastCons470way/output_hg38ToBosTau9/
	filelist=(${dir_liftOver_chunks}/*.hg38ToBosTau9.bed.gz)
	cat ${{filelist[*]}} > ./output_hg38ToBosTau9/All.hg38ToBosTau9.bed.gz
	
	## generate gene position bed
	for CHR in `seq 1 29`
			do
				cat ${gene_gtf} | awk -F"\t" -v "chr=$CHR" '{{if($1==chr && $3=="gene")print $1"\t"$4-1"\t"$5-1"\t"$9}}' |sed 's/"/\t/g' |awk '{print $1 "\t" $2 "\t" $3 "\t" $5}'|sort -k2,2n >./gene_annot/pcg_annot.chr${CHR}.bed
				bedtools coverage -a ./gene_annot/pcg_annot.chr${CHR}.bed -b ./output_hg38ToBosTau9/Cattle.chr${CHR}.hg38ToBosTau9.bed.gz > ./output_phastCons_pcg/Cattle.chr${CHR}.gene_coverage.txt
			done
			
	## 	merge all the fastcons scores of all chromosomes	
	
	cat ./output_phastCons_pcg/Cattle.chr*.phastCons_pcg.txt > ./output_phastCons_pcg/Cattle.chrAll.phastCons_pcg.txt
	awk 'BEGIN {OFS="\t"} {if ($5 == ".") $5 = "0"; print}' ./output_phastCons_pcg/Cattle.chrAll.phastCons_pcg.txt  |sed '1i #chr\tstart\tend\tgene_id\tPhastCons' > ./output_phastCons_pcg/Cattle.chrAll.phastCons_pcg_final.txt