#####
step3 Perform genotype imputation per bin using GLIMPSE2
#####
# cat bins.txt | while read bin

conda activate glimpse2
cd {params.workpath}/bqsr_bamlist

##Collect all BAM files generated by GATK BQSR
ls *.bam > bamlist

GLIMPSE2_phase \
            --bam-list ./bamlist --reference /faststorage/project/farmgtex/gtex/cattle_ref/SNPs/split/split_${bin}.bin \
            --output /faststorage/project/farmgtex/gtex/VCFfile/${bin}.bcf --threads 12
